bag/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.bag, name="bag"),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

betterTogether/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('guides/', views.guides, name="guides"),
    path('merchandise/', views.merch, name="merch"),
    path('<merch1_id>', views.merch_detail, name='merch_detail'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from products.models import merchandise


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = models.CharField(max_length=40, null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper() # generates a random string we can use as order number 

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum']
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(merchandise, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True) # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models

# Create your models here.


class Gallery(models.Model):

    class Meta:
        verbose_name_plural = "Gallery" # how the model is displayed in the admin page

    name = models.CharField(max_length=254, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    image_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class nutritionGuides(models.Model):

    class Meta:
        verbose_name_plural = "Nutrition Guides" # how the model is displayed in the admin page

    title = models.CharField(max_length=254, null=True, blank=True) 
    description = models.TextField(max_length=254, null=True, blank=True)
    price = models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=100)

    def __str__(self):
        return self.title


class merchandise(models.Model):

    class Meta:
        verbose_name_plural = "Merch" # how the model is displayed in the admin page

    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default = False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=0, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from products.models import Gallery
from products.models import nutritionGuides
from products.models import merchandise

# Create your views here.


def guides(request):

    gallery = Gallery.objects.all()  # gets the images from the gallery model 
    guides = nutritionGuides.objects.all()  # gets all the info from the nutrition guides.

    context = {
        'gallery': gallery,
        'guides': guides,
    }
 
    return render(request, 'products/guides.html', context)


#view to return the merch page

def merch(request):

    merch = merchandise.objects.all()
    query = None

    if request.GET:
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))
            
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            merch = merch.filter(queries)

    context = {
        'merch': merch,
        'search_term': query,
    }

    return render(request, 'products/merchandise.html', context)


def merch_detail(request, merch1_id):
    """ A view to show individual product details """

    merch1 = get_object_or_404(merchandise, pk=merch1_id)

    context = {
        'merch1': merch1,
    }

    return render(request, 'products/merch_details.html', context)

products/templates/products/guides.html
{% extends 'base.html' %} 
{% load static %}


{% block content %}

<div class="row container-fluid sectionRow">
    <p class="guides">Guides</p>
    <p class="aboutGuides">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, assumenda! Tempora eum
        fugiat saepe debitis temporibus nisi officia voluptate. Provident, culpa ipsam facere nemo repellat nisi id
        magnam recusandae alias?</p>
</div>
<div class="row container-fluid sectionRow">
    <div class="col-sm-6">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for G in gallery %}
                {% if forloop.first %}
                <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter0}}" class="active"></li>
                {% else %}
                <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter0}}"></li>

                {% endif %}
                {% endfor %}
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>

            <div class="carousel-inner">
                {% for G in gallery %}
                {% if forloop.first %}
                <div class="carousel-item active  ">
                    {% else %}
                    <div class="carousel-item  ">
                        {% endif %}
                        <img class="CarouselImage" src="{{ G.image.url }}" alt="{{G.name}}">
                    </div>

                    {% endfor %}
                </div>

                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col-sm-6 nutritionGuides">
        {% for NutGu in guides %}
        <p class="title">{{ NutGu.title }}</p>
        <p class="desc">{{ NutGu.description }}</p>
        <p class="price">£{{ NutGu.price }}</p> 
        
        {% endfor %}
            
    </div>
    </div>
    
</div>

{% endblock %}

products/templates/products/merch_details.html
{% extends 'base.html' %} 
{% load static %}


{% block content %}


<div class="row container-fluid sectionRow mt-5">
  <div class="col-lg-4 h-50 w-50">
    <img src="{{ merch1.image.url }}" class="h-50 merchDetailImage" alt="{{ merch1.image_url }}">
  </div>
  <div class="col-lg-8 merchDetailsInfo">
    <h1>{{ merch1.name }}</h1> 
    <br>
    <p>{{ merch1.description }}</p>
    <p>${{ merch1.price }}</p>
    <p>Rating: {{ merch1.rating }}/5</p>
    <form class="form" action="{% url 'add_to_bag' merch1.id %}" method="POST">
  {% csrf_token %}
  <div class="form-row">
      <div class="col-12">
        {% with merch1.has_sizes as s %}
        {% if s %}
                <p><strong>Size:</strong></p>
                <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                    <option value="xs">XS</option>
                    <option value="s">S</option>
                    <option value="m" selected>M</option>
                    <option value="l">L</option>
                    <option value="xl">XL</option>
                </select>
        {% endif %}

          <p class="mt-3"><strong>Quantity:</strong></p>
          <div class="form-group w-50">
              <div class="input-group">
                <div class="input-group-prepend">
                  <button class="decrement-qty btn rounded-0" 
                      data-item_id="{{ merch1.id }}" id="decrement-qty_{{ merch1.id }}">
                      <span class="icon">
                          <i class="fas fa-minus"></i>
                      </span>
                  </button>
              </div>
                  <input class="form-control qty_input" type="number" name="quantity" value="1" min="1" max="99" data-item_id="{{ merch1.id }}" id="id_qty_{{ merch1.id }}">
                  <div class="input-group-append">
                    <button class="increment-qty btn rounded-0"
                        data-item_id="{{ merch1.id }}" id="increment-qty_{{ merch1.id }}">
                        <span class="icon">
                            <i class="fas fa-plus"></i>
                        </span>
                    </button>
                </div>
              </div>
          </div>
      </div>

      <div class="col-12">
          <a href="{% url 'merch' %}" class="btn rounded-0 mt-5">
              <span class="icon">
                  <i class="fas fa-chevron-left"></i>
              </span>
              <span class="text-uppercase">Keep Shopping</span>
          </a>
          <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag">
      </div>
      <input type="hidden" name="redirect_url" value="{{ request.path }}">
      {% endwith %} 
  </div>
</form>
  </div>
</div>


{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}

products/templates/products/merchandise.html
{% extends 'base.html' %} 
{% load static %}


{% block content %}

<div class="row container-fluid sectionRow">
    <p class="guides">Merchandise</p>
    <p class="aboutGuides">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, assumenda! Tempora eum
        fugiat saepe debitis temporibus nisi officia voluptate. Provident, culpa ipsam facere nemo repellat nisi id
        magnam recusandae alias?</p>
        <!-- search for merchandise page.-->
        <form method="GET" action="{% url 'merch' %}" class="d-block m-auto">
          <div class="input-group w-100">
              <input class="form-control border border-black rounded-0" type="text" name="q" placeholder="Search our merch...">
              <div class="input-group-append">
                  <button class="form-control btn btn-black border border-black rounded-0" type="submit">
                      <span class="icon">
                          <i class="fas fa-search"></i>
                      </span>
                  </button>
              </div>
          </div>
      </form>
</div>


<div class="row container-fluid sectionRow">
    {% for M in merch %}
    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3 mb-5 mt-3">
    <div class="card h-100 border-0 ">
        <a href="{% url 'merch_detail' M.id %}" class="h-100"> 
        <img src="{{ M.image.url }}" class="card-img-top" alt="{{ M.image_url }}">
    </a>
        <div class="card-body">
          <h5 class="card-title">{{ M.name }}</h5>
          <p class="card-text">${{ M.price }}</p>
        </div>
      </div>
    </div>
      {% endfor %}
</div>


   


{% endblock %}